# Generated by Django 5.2.5 on 2025-08-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("description", models.TextField()),
                ("pages", models.PositiveIntegerField()),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (5, "★★★★★ - Excellent"),
                            (4, "★★★★☆ - Good"),
                            (2, "★★☆☆☆ - Poor"),
                            (3, "★★★☆☆ - Average"),
                            (1, "★☆☆☆☆ - Terrible"),
                        ]
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("FIC", "Fiction"),
                            ("NF", "Non-Fiction"),
                            ("SCI", "Science Fiction"),
                            ("FAN", "Fantasy"),
                            ("ROM", "Romance"),
                            ("THR", "Thriller"),
                            ("BIO", "Biography"),
                            ("MYS", "Mystery"),
                            ("HIS", "Historical"),
                            ("POE", "Poetry"),
                        ]
                    ),
                ),
            ],
        ),
    ]
