# Generated by Django 5.2.5 on 2025-08-29 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                ("authorID", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("dateOfBirth", models.DateField(null=True)),
                ("nationality", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="book",
            name="rating",
            field=models.IntegerField(
                choices=[
                    (5, "★★★★★ - Excellent"),
                    (1, "★☆☆☆☆ - Terrible"),
                    (2, "★★☆☆☆ - Poor"),
                    (3, "★★★☆☆ - Average"),
                    (4, "★★★★☆ - Good"),
                ]
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="books.author",
            ),
        ),
    ]
