# Generated by Django 5.2.5 on 2025-08-31 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0008_alter_book_rating"),
    ]

    operations = [
        migrations.RenameField(
            model_name="author",
            old_name="authorID",
            new_name="author_id",
        ),
        migrations.AlterField(
            model_name="book",
            name="rating",
            field=models.IntegerField(
                choices=[
                    (4, "★★★★☆ - Good"),
                    (5, "★★★★★ - Excellent"),
                    (3, "★★★☆☆ - Average"),
                    (1, "★☆☆☆☆ - Terrible"),
                    (2, "★★☆☆☆ - Poor"),
                ]
            ),
        ),
    ]
