# Generated by Django 5.2.5 on 2025-08-31 23:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0009_rename_authorid_author_author_id_alter_book_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="publised_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="book",
            name="rating",
            field=models.IntegerField(
                choices=[
                    (5, "★★★★★ - Excellent"),
                    (1, "★☆☆☆☆ - Terrible"),
                    (4, "★★★★☆ - Good"),
                    (2, "★★☆☆☆ - Poor"),
                    (3, "★★★☆☆ - Average"),
                ]
            ),
        ),
    ]
