# Generated by Django 5.2.5 on 2025-09-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0011_alter_book_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="rating",
            field=models.IntegerField(
                choices=[
                    (2, "★★☆☆☆ - Poor"),
                    (4, "★★★★☆ - Good"),
                    (5, "★★★★★ - Excellent"),
                    (3, "★★★☆☆ - Average"),
                    (1, "★☆☆☆☆ - Terrible"),
                ]
            ),
        ),
    ]
